name: Local Config
version: 1.0.0
schema: v1
models:
  - name: qwen2.5-coder
    provider: ollama
    model: qwen2.5-coder-7b-instruct-q4_k_m:latest
    roles:
      - chat
      - edit
      - apply
  - name: Qwen2.5-Coder 1.5B
    provider: ollama
    model: qwen2.5-coder-7b-instruct-q4_k_m:latest
    roles:
      - autocomplete
  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed
      
